---

#---------------------------------------------------
# DHCP Security Group
#---------------------------------------------------

- name: Create dhcp security group
  ec2_group:
   name: "{{ ec2_security_group_dhcp }}"
   description: "Default security group that allows all instances to enable cockpit service."
   vpc_id: "{{ vpc_id }}"
   region: "{{ aws_region }}"
   state: "present"
   rules:
    - proto: "udp"
      from_port: "{{ dhcp_port }}"
      to_port: "{{ dhcp_port }}"
      cidr_ip: "{{ public_route_cidr_block }}"
   rules_egress: []