---

#---------------------------------------------------
# Subnet
#---------------------------------------------------

- name: Create public subnet
  ec2_vpc_subnet:
   vpc_id: "{{ vpc_id }}"
   cidr: "{{ public_subnet_1_cidr }}"
   az: "{{ aws_region }}a"
   region: "{{ aws_region }}"
   tags:
    Name: "{{ vpc_subnet_tag }}"
    namespace: "{{ namespace }}"
  register: subnet_facts

- name: Set subnet fact
  set_fact:
   public_subnet_id: "{{ subnet_facts['subnet']['id'] }}"