---

#---------------------------------------------------
# Route53
#---------------------------------------------------

- name: Create private zone
  route53_zone:
     zone: "{{ intranet }}"
     state: "present"
     vpc_id: "{{ vpc_id }}"
     vpc_region: "{{ aws_region }}"
     comment: "Internal zone for {{ namespace }}"
  register: private_zone

# - debug: msg="{{ private_zone }}"

- name: Set private zone id fact
  set_fact:
    private_zone_id: "{{ private_zone['result']['zone_id'] }}"

- name: Create private record
  route53:
    hosted_zone_id: "{{ private_zone_id }}"
    zone: "{{ intranet }}"
    record: "{{ ec2_tag }}.{{ intranet }}"
    type: A
    ttl: 300
    value: "{{ private_ip }}"
    wait: yes
    vpc_id: "{{ vpc_id }}"
    private_zone: true
    command: "create"
    overwrite: yes
